### ISSUE TITLE
如何解决局域网无法映射到公网的问题？

### ISSUE THREAD

**Issue by gqcdash** [zy445566/ipfs-doc-zh#1]
如题。
最近在写一个基于IPFS的无服务器的桌面聊天工具。目前能做出局域网内的实时通信，但跨网域无法实现（其实是可以的，但是信息发布极其缓慢，无法满足实时通信的需求）。
看到网上有比较成熟的比如Orbit，基于web的。想问一下大佬们有没有关于纯桌面端的解决方案。

**Comment by zy445566** [comment]
抱歉这一块不是特别清楚，但如果是借助sub和pub那么，跨局域网通讯必须要有一台在公网的ipfs服务进行打洞。信息发布缓慢我认为应该是公网的ipfs距离比较远或者拥堵导致不是特别稳定，你可以试一下自己在公网的ip上部署一个ipfs服务，再在需要通讯的机器中的bootstraplist增加你在公网的ipfs的ip同时清除其他ip尝试，情况应该会好转。毕竟大陆的公网机器节点不是很多，且很多被用作了其他用途，所以的确会有拥挤的现象。
